"""
train.py — Train a CNN apnea event classifier and export to TFLite (INT8).

Input:  data/manifest.csv  (generated by data/synthesize.py)
Output: train/apnea_model.tflite  (~120 KB after quantisation)
        train/label_map.json       {"0":"silence","1":"snoring",...}

Architecture:
  Input: log-mel spectrogram (64 mel bins × 32 time frames × 1 channel)
  Conv2D(32,3×3) → BN → ReLU → MaxPool(2×2)
  Conv2D(64,3×3) → BN → ReLU → MaxPool(2×2)
  Conv2D(128,3×3) → BN → ReLU
  GlobalAveragePooling2D
  Dense(64, ReLU) → Dropout(0.3)
  Dense(5, Softmax)

Usage:
  python train/train.py
  python train/train.py --epochs 40 --batch 64
"""

import argparse
import json
import os
import sys
import csv
from pathlib import Path

import numpy as np
import librosa
import soundfile as sf
from tqdm import tqdm

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

SR          = 16000
CLIP_SECS   = 2.0
N_MELS      = 64
N_FRAMES    = 32    # time frames in spectrogram (hop_length = SR*CLIP_SECS/N_FRAMES = 1000)
HOP_LENGTH  = int(SR * CLIP_SECS / N_FRAMES)   # 1000 samples
N_FFT       = 1024
FMIN        = 50
FMAX        = 4000  # respiratory sounds live below 4 kHz
NUM_CLASSES = 5

LABEL_MAP = {0: "silence", 1: "snoring", 2: "cessation", 3: "gasp", 4: "recovery"}


# ---------------------------------------------------------------------------
# Feature extraction
# ---------------------------------------------------------------------------

def wav_to_melspec(path: str) -> np.ndarray:
    """Load a WAV clip and return a (N_MELS, N_FRAMES, 1) float32 array."""
    y, sr = sf.read(path, dtype="float32")
    if sr != SR:
        y = librosa.resample(y, orig_sr=sr, target_sr=SR)
    # Pad / trim to exactly CLIP_SECS
    target_len = int(SR * CLIP_SECS)
    if len(y) < target_len:
        y = np.pad(y, (0, target_len - len(y)))
    else:
        y = y[:target_len]

    mel = librosa.feature.melspectrogram(
        y=y, sr=SR, n_fft=N_FFT, hop_length=HOP_LENGTH,
        n_mels=N_MELS, fmin=FMIN, fmax=FMAX
    )
    log_mel = librosa.power_to_db(mel, ref=np.max)   # range roughly [-80, 0]
    # Normalise to [0, 1]
    log_mel = (log_mel + 80.0) / 80.0
    log_mel = np.clip(log_mel, 0.0, 1.0)

    # Ensure shape (N_MELS, N_FRAMES)
    if log_mel.shape[1] < N_FRAMES:
        log_mel = np.pad(log_mel, ((0, 0), (0, N_FRAMES - log_mel.shape[1])))
    else:
        log_mel = log_mel[:, :N_FRAMES]

    return log_mel[..., np.newaxis].astype(np.float32)   # (64, 32, 1)


# ---------------------------------------------------------------------------
# Dataset loading
# ---------------------------------------------------------------------------

def load_dataset(manifest_path: str, split: str):
    """Return (X, y) numpy arrays for the requested split."""
    rows = []
    with open(manifest_path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row["split"] == split:
                rows.append((row["path"], int(row["label_idx"])))

    X = np.zeros((len(rows), N_MELS, N_FRAMES, 1), dtype=np.float32)
    y = np.zeros(len(rows), dtype=np.int32)

    for i, (path, label) in enumerate(tqdm(rows, desc=f"Loading {split}")):
        X[i] = wav_to_melspec(path)
        y[i] = label

    return X, y


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

def build_model() -> "tf.keras.Model":
    import tensorflow as tf
    inp = tf.keras.Input(shape=(N_MELS, N_FRAMES, 1), name="input")

    x = tf.keras.layers.Conv2D(32, (3, 3), padding="same", use_bias=False)(inp)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.ReLU()(x)
    x = tf.keras.layers.MaxPooling2D((2, 2))(x)

    x = tf.keras.layers.Conv2D(64, (3, 3), padding="same", use_bias=False)(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.ReLU()(x)
    x = tf.keras.layers.MaxPooling2D((2, 2))(x)

    x = tf.keras.layers.Conv2D(128, (3, 3), padding="same", use_bias=False)(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.ReLU()(x)

    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dense(64, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.3)(x)
    out = tf.keras.layers.Dense(NUM_CLASSES, activation="softmax", name="output")(x)

    model = tf.keras.Model(inputs=inp, outputs=out)
    return model


# ---------------------------------------------------------------------------
# TFLite export with INT8 quantisation
# ---------------------------------------------------------------------------

def export_tflite(model, X_train: np.ndarray, output_path: str):
    import tensorflow as tf

    def representative_dataset():
        # Sample 200 clips for calibration
        indices = np.random.choice(len(X_train), size=min(200, len(X_train)), replace=False)
        for idx in indices:
            yield [X_train[idx:idx+1]]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.float32  # keep float I/O for easier Android integration
    converter.inference_output_type = tf.float32

    tflite_model = converter.convert()
    with open(output_path, "wb") as f:
        f.write(tflite_model)
    size_kb = len(tflite_model) / 1024
    print(f"TFLite model written: {output_path}  ({size_kb:.0f} KB)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", default="data/manifest.csv")
    parser.add_argument("--epochs",   type=int, default=30)
    parser.add_argument("--batch",    type=int, default=64)
    parser.add_argument("--lr",       type=float, default=1e-3)
    parser.add_argument("--out_dir",  default="train")
    args = parser.parse_args()

    import tensorflow as tf
    print(f"TensorFlow {tf.__version__}  |  GPUs: {tf.config.list_physical_devices('GPU')}")

    Path(args.out_dir).mkdir(exist_ok=True)

    # Save label map
    label_map_path = Path(args.out_dir) / "label_map.json"
    with open(label_map_path, "w") as f:
        json.dump(LABEL_MAP, f, indent=2)
    print(f"Label map saved: {label_map_path}")

    # Load data
    print("\nLoading training data…")
    X_train, y_train = load_dataset(args.manifest, "train")
    print("Loading validation data…")
    X_val,   y_val   = load_dataset(args.manifest, "val")

    print(f"\nTrain: {X_train.shape}  Val: {X_val.shape}")
    print(f"Class distribution (train): { {LABEL_MAP[i]: int((y_train==i).sum()) for i in range(NUM_CLASSES)} }")

    # Build + compile
    model = build_model()
    model.summary()

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=args.lr),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )

    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor="val_accuracy", patience=6, restore_best_weights=True, verbose=1
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss", factor=0.5, patience=3, min_lr=1e-5, verbose=1
        ),
        tf.keras.callbacks.ModelCheckpoint(
            str(Path(args.out_dir) / "best_model.keras"),
            monitor="val_accuracy", save_best_only=True, verbose=1
        ),
    ]

    # Train
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=args.epochs,
        batch_size=args.batch,
        callbacks=callbacks,
        verbose=1,
    )

    # Evaluate on test split
    print("\nLoading test data…")
    X_test, y_test = load_dataset(args.manifest, "test")
    loss, acc = model.evaluate(X_test, y_test, verbose=0)
    print(f"\nTest accuracy: {acc*100:.1f}%  |  Test loss: {loss:.4f}")

    # Per-class accuracy
    preds = np.argmax(model.predict(X_test, verbose=0), axis=1)
    for i, name in LABEL_MAP.items():
        mask = y_test == i
        if mask.sum() > 0:
            cls_acc = (preds[mask] == i).mean() * 100
            print(f"  {name:12s}: {cls_acc:.1f}%  (n={mask.sum()})")

    # Export TFLite
    tflite_path = str(Path(args.out_dir) / "apnea_model.tflite")
    print(f"\nExporting INT8 TFLite model → {tflite_path}")
    export_tflite(model, X_train, tflite_path)

    # Save training history
    hist_path = Path(args.out_dir) / "history.json"
    with open(hist_path, "w") as f:
        json.dump({k: [float(v) for v in vs] for k, vs in history.history.items()}, f, indent=2)
    print(f"Training history saved: {hist_path}")

    print("\nPhase 2 Day 2 complete — model ready for Android integration.")


if __name__ == "__main__":
    main()
